### ISSUE TITLE
Support for @mui v5

### ISSUE THREAD

**Issue by GhostyJade** [harish-everest/react-phone-input-mui#4]
Are there any plans to add support to this package to @mui v5?
If you need I can help u by making a pull request with the update

Thanks

**Comment by ruiaraujo012** [comment]
same here

**Comment by harish-everest** [comment]
I will try to upgrade Mui to v5 and shout out if I need help.

**Comment by harish-everest** [comment]
@GhostyJade @ruiaraujo012  
Published a new package to support Mui v5. Let me know if you face any errors or any feedback that I need to incorporate?

**Comment by harish-everest** [comment]
I have added support for material-ui v5. Closing this issue as of now. Raise a new issue or PR if you find any issues. 

Thank you for using this and trying to improve this.
