### ISSUE TITLE
Issue with label

### ISSUE THREAD

**Issue by GhostyJade** [harish-everest/react-phone-input-mui#6]
Hi
After some testing with the new package version, I've found that there are some issues with the label.
(I'm using a TextField with the "filled" variant)
If i pass directly the label or the specialLabel prop to the component, it's rendered outside the component,
If i pass undefined to the same props, it uses "Phone" as the localization string and it's rendered outside,
If i pass the label into the inputProps object, the label is correctly rendered in the TextField but another label is added outside (see the attached image)

![photo_2022-02-14_15-48-47](https://user-images.githubusercontent.com/38327334/153886643-da1c3d58-3446-4d64-8af4-75fe2b089343.jpg)

If u need more info or a CodeSandbox example I'm there
Thanks in advance

**Comment by harish-everest** [comment]
@GhostyJade I have made the changes. Let me know if these looks good for you.

<img width="605" alt="Screenshot 2022-02-14 at 10 07 10 PM" src="https://user-images.githubusercontent.com/48308300/153906334-45be6f40-1374-4d06-b7ae-51dc8492591c.png">

**Comment by GhostyJade** [comment]
The label placement is right, the only suggestion I have is to apply more padding to left to the start adornment, and then it'll look perfect
Thanks for your time

**Comment by GhostyJade** [comment]
Thanks so much, when you'll publish on npm I'll test it on our project and I'll give you feedback again

**Comment by harish-everest** [comment]
Already published a new version

**Comment by GhostyJade** [comment]
It works, thanks again! c:
