### ISSUE TITLE
Dropdown and flags menu style error

### ISSUE THREAD

**Issue by Stefifox** [harish-everest/react-phone-input-mui#9]
Using this component I'm noticing a problem with style, there is some code or import to fix this?

![image](https://user-images.githubusercontent.com/30950154/154237475-e8c2bb90-b3df-4284-9f70-36bf3880f9b7.png)
![image](https://user-images.githubusercontent.com/30950154/154237484-0948e786-1b6d-4196-a470-b016efd27529.png)

My import:
```
import ReactPhoneInput from 'react-phone-input-material-ui';
import 'react-phone-input-material-ui/lib/style.css';
```

My Code:
```
<ReactPhoneInput
	name={name}
	disabled={!isEdit}
	value={value}
	component={TextField}
	country="it"
	inputProps={{ variant: 'filled', label, required }}
	fullWidth
	onChange={val => setValue(val)}
	onBlur={onBlur}
	// onKeyDown={e => e.key === 'Enter' && onBlur(e)}
	defaultErrorMessage={!!errorMessage && !isPristine}
	helperText={errorMessage && !isPristine ? errorMessage : null}
/>
```

**Comment by harish-everest** [comment]
You can try importing `'react-phone-input-material-ui/lib/plain.css'` and if this fixes the styles. Else I will work on it or you can open a PR for a fix.

**Comment by Stefifox** [comment]
I've tried to import your style but this is the result
![image](https://user-images.githubusercontent.com/30950154/154700261-8dae78cf-ae60-42e0-a01d-f3dfc51eab1d.png)

**Comment by harish-everest** [comment]
Hi @Stefifox 

You can use `import 'react-phone-input-material-ui/lib/style.css';`. Let me know if you still face styling issues.

**Comment by harish-everest** [comment]
@Stefifox I'm unable to replicate the styling issue. I tried with the same code as yours. Please provide a codesandbox demo  so that I can debug this.

**Comment by harish-everest** [comment]
Hi, @Stefifox closing this issue as we don't have any response on this.
